"""init

Revision ID: 79a640815a1b
Revises: 
Create Date: 2026-05-04 06:37:46.034850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '79a640815a1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('telegram_group_id', sa.BigInteger(), nullable=False, comment='Telegram 群组 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='群组名称'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='群组公开用户名'),
    sa.Column('chat_type', sa.Enum('GROUP', 'SUPERGROUP', name='enum_group_chat_type', native_enum=False, create_constraint=True), server_default='supergroup', nullable=False, comment='群组类型'),
    sa.Column('description', sa.Text(), nullable=True, comment='群组描述'),
    sa.Column('owner_telegram_user_id', sa.BigInteger(), nullable=True, comment='群主 Telegram 用户 ID'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='是否启用清理'),
    sa.Column('settings', sa.Text(), nullable=True, comment='群组维度的检测和处置配置'),
    sa.Column('bot_permissions', sa.Text(), nullable=True, comment='机器人在群里的权限配置'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='最近一条消息时间'),
    sa.Column('is_authorized', sa.Boolean(), server_default='0', nullable=False, comment='是否已授权使用机器人'),
    sa.Column('info_updated_at', sa.DateTime(), nullable=True, comment='上次从 Telegram 同步群组信息的时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index(op.f('ix_groups_telegram_group_id'), 'groups', ['telegram_group_id'], unique=True)
    op.create_table('group_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='所属群组主键'),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False, comment='Telegram 用户 ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment='名'),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment='姓'),
    sa.Column('language_code', sa.String(length=16), nullable=True, comment='语言代码'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'RESTRICTED', name='enum_group_user_role', native_enum=False, create_constraint=True), server_default='member', nullable=False, comment='群内角色'),
    sa.Column('status', sa.Enum('ACTIVE', 'LEFT', 'KICKED', 'BANNED', name='enum_group_user_status', native_enum=False, create_constraint=True), server_default='active', nullable=False, comment='成员状态'),
    sa.Column('is_bot', sa.Boolean(), server_default='0', nullable=False, comment='是否机器人账号'),
    sa.Column('is_whitelisted', sa.Boolean(), server_default='0', nullable=False, comment='是否白名单成员'),
    sa.Column('joined_at', sa.DateTime(), nullable=True, comment='入群时间'),
    sa.Column('left_at', sa.DateTime(), nullable=True, comment='离群时间'),
    sa.Column('profile_extra', sa.Text(), nullable=True, comment='补充资料'),
    sa.Column('profile_updated_at', sa.DateTime(), nullable=True, comment='上次从 Telegram 同步用户资料的时间'),
    sa.Column('is_deactivated', sa.Boolean(), server_default='0', nullable=False, comment='是否已注销账号；Telegram 封禁用户后其账号会变为已注销状态'),
    sa.Column('warn_count', sa.Integer(), server_default='0', nullable=False, comment='累计警告次数，用于触发自动升级惩罚策略'),
    sa.Column('muted_until', sa.DateTime(), nullable=True, comment='临时禁言到期时间；NULL 且 status=BANNED 时表示永久禁言或未禁言（结合 status 判断）'),
    sa.Column('restriction_until', sa.DateTime(), nullable=True, comment='权限限制（RESTRICT）到期时间；NULL 表示未限制或已解除'),
    sa.Column('kicked_at', sa.DateTime(), nullable=True, comment='最近一次被踢出群组的时间'),
    sa.Column('ban_reason', sa.Text(), nullable=True, comment='封禁原因，由管理员填写或由系统自动生成'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('left_at IS NULL OR joined_at IS NULL OR left_at >= joined_at', name=op.f('ck_group_users_ck_group_users_left_after_joined')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_users_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_users')),
    sa.UniqueConstraint('group_id', 'telegram_user_id', name='uq_group_users_group_user')
    )
    op.create_index('ix_group_users_group_role', 'group_users', ['group_id', 'role'], unique=False)
    op.create_index('ix_group_users_group_status', 'group_users', ['group_id', 'status'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='所属群组主键'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='规则编码'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='规则名称'),
    sa.Column('rule_type', sa.Enum('KEYWORD', 'REGEX', 'URL', 'USERNAME', 'CONTACT', 'AI', name='enum_rule_type', native_enum=False, create_constraint=True), nullable=False, comment='规则类型'),
    sa.Column('pattern', sa.Text(), nullable=True, comment='关键词或正则'),
    sa.Column('action', sa.Enum('DELETE', 'WARN', 'MUTE', 'PERMANENT_MUTE', 'RESTRICT', 'KICK', 'BAN', 'REVIEW', 'IGNORE', name='enum_rule_action', native_enum=False, create_constraint=True), server_default='delete', nullable=False, comment='命中后动作'),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False, comment='优先级'),
    sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=False, comment='是否启用'),
    sa.Column('options', sa.Text(), nullable=True, comment='规则额外配置'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('priority >= 0', name=op.f('ck_rules_ck_rules_priority_non_negative')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_rules_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules')),
    sa.UniqueConstraint('group_id', 'code', name='uq_rules_group_code')
    )
    op.create_index(op.f('ix_rules_code'), 'rules', ['code'], unique=False)
    op.create_index(op.f('ix_rules_group_id'), 'rules', ['group_id'], unique=False)
    op.create_table('group_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='所属群组主键'),
    sa.Column('sender_id', sa.BigInteger(), nullable=True, comment='发送者群组用户主键'),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False, comment='Telegram 消息 ID'),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True, comment='发送者 Telegram 用户 ID'),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True, comment='被回复消息 ID'),
    sa.Column('message_type', sa.Enum('TEXT', 'PHOTO', 'VIDEO', 'DOCUMENT', 'STICKER', 'FORWARDED', 'OTHER', name='enum_group_message_type', native_enum=False, create_constraint=True), server_default='text', nullable=False, comment='消息类型'),
    sa.Column('content_text', sa.Text(), nullable=True, comment='文本内容'),
    sa.Column('content_extra', sa.Text(), nullable=True, comment='媒体、链接、按钮等补充内容'),
    sa.Column('raw_payload', sa.Text(), nullable=True, comment='Telegram 原始更新片段'),
    sa.Column('risk_score', sa.Float(), nullable=True, comment='广告风险分'),
    sa.Column('hit_rule_code', sa.String(length=64), nullable=True, comment='命中的规则编码'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('sent_at', sa.DateTime(), nullable=False, comment='消息发送时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 1)', name=op.f('ck_group_messages_ck_group_messages_risk_score_range')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_messages_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['group_users.id'], name=op.f('fk_group_messages_sender_id_group_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_messages')),
    sa.UniqueConstraint('group_id', 'telegram_message_id', name='uq_group_messages_group_msg')
    )
    op.create_index('ix_group_messages_group_deleted', 'group_messages', ['group_id', 'is_deleted'], unique=False)
    op.create_index('ix_group_messages_group_sent_at', 'group_messages', ['group_id', 'sent_at'], unique=False)
    op.create_table('moderation_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='所属群组主键'),
    sa.Column('message_id', sa.BigInteger(), nullable=True, comment='关联消息主键'),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True, comment='被处置成员主键'),
    sa.Column('rule_id', sa.BigInteger(), nullable=True, comment='命中规则主键'),
    sa.Column('action', sa.Enum('DELETE', 'WARN', 'MUTE', 'PERMANENT_MUTE', 'RESTRICT', 'KICK', 'BAN', 'REVIEW', 'IGNORE', name='enum_moderation_action', native_enum=False, create_constraint=True), nullable=False, comment='执行动作'),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='enum_moderation_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False, comment='执行状态'),
    sa.Column('reason', sa.Text(), nullable=True, comment='处置原因'),
    sa.Column('result_detail', sa.Text(), nullable=True, comment='执行结果和补充细节'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_moderation_records_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['group_messages.id'], name=op.f('fk_moderation_records_message_id_group_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_moderation_records_rule_id_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['group_users.id'], name=op.f('fk_moderation_records_target_user_id_group_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_records'))
    )
    op.create_index(op.f('ix_moderation_records_group_id'), 'moderation_records', ['group_id'], unique=False)
    op.create_index('ix_moderation_records_group_status', 'moderation_records', ['group_id', 'status'], unique=False)
    op.create_table('notification_recall_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='所属群组主键'),
    sa.Column('moderation_record_id', sa.BigInteger(), nullable=True, comment='关联处置记录主键'),
    sa.Column('chat_id', sa.BigInteger(), nullable=False, comment='Telegram chat_id'),
    sa.Column('notification_message_id', sa.BigInteger(), nullable=False, comment='待撤回的通知消息 ID'),
    sa.Column('recall_after_seconds', sa.Integer(), server_default='5', nullable=False, comment='延迟撤回秒数，默认 5 秒，最小 5 秒'),
    sa.Column('scheduled_recall_at', sa.DateTime(), nullable=False, comment='计划撤回时间'),
    sa.Column('recalled_at', sa.DateTime(), nullable=True, comment='实际撤回时间'),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELED', name='enum_notification_recall_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False, comment='撤回执行状态'),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False, comment='撤回执行尝试次数'),
    sa.Column('fail_reason', sa.Text(), nullable=True, comment='撤回失败原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('recall_after_seconds >= 5', name=op.f('ck_notification_recall_records_ck_notification_recalls_min_delay_5')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_notification_recall_records_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderation_record_id'], ['moderation_records.id'], name=op.f('fk_notification_recall_records_moderation_record_id_moderation_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_recall_records'))
    )
    op.create_index(op.f('ix_notification_recall_records_group_id'), 'notification_recall_records', ['group_id'], unique=False)
    op.create_index(op.f('ix_notification_recall_records_moderation_record_id'), 'notification_recall_records', ['moderation_record_id'], unique=False)
    op.create_index('ix_notification_recalls_group_status', 'notification_recall_records', ['group_id', 'status'], unique=False)
    op.create_index('ix_notification_recalls_status_scheduled', 'notification_recall_records', ['status', 'scheduled_recall_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_recalls_status_scheduled', table_name='notification_recall_records')
    op.drop_index('ix_notification_recalls_group_status', table_name='notification_recall_records')
    op.drop_index(op.f('ix_notification_recall_records_moderation_record_id'), table_name='notification_recall_records')
    op.drop_index(op.f('ix_notification_recall_records_group_id'), table_name='notification_recall_records')
    op.drop_table('notification_recall_records')
    op.drop_index('ix_moderation_records_group_status', table_name='moderation_records')
    op.drop_index(op.f('ix_moderation_records_group_id'), table_name='moderation_records')
    op.drop_table('moderation_records')
    op.drop_index('ix_group_messages_group_sent_at', table_name='group_messages')
    op.drop_index('ix_group_messages_group_deleted', table_name='group_messages')
    op.drop_table('group_messages')
    op.drop_index(op.f('ix_rules_group_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_code'), table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_group_users_group_status', table_name='group_users')
    op.drop_index('ix_group_users_group_role', table_name='group_users')
    op.drop_table('group_users')
    op.drop_index(op.f('ix_groups_telegram_group_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
